### ISSUE TITLE
Protocol counter

### ISSUE THREAD

**Issue by loblik** [openeizo/openeizo#2]
Hello,

thanks for your work. I have two ev2456 and I also started looking into this. I was just thinking about some quicker more hacky python/hidapi userspace solution.

Do you know what's the reason for the counter in the protocol? Probably to identify different applications? So application is supposed to get a new value at startup and use that during its runtime? This counter survives power off and even factory reset of the monitor. Hopefully it overflows to zero after it reaches 65535.

**Comment by loblik** [comment]
Ok. It does not survive power-off. I was talking to other display then I thought.

**Comment by markbolhuis** [comment]
Hi there, I'm not sure what that counter is for, I'm just replicating what the Screen-InStyle software does.
It may very well be for identification of different applications, although I'm not sure why the monitor would need to keep track of that.
And yes the counter does overflow to 0.
